CREATE TABLE {provider_prefix}_cdr_by_uid (uid string, arr ARRAY<ARRAY<string>>)
PARTITIONED BY (pdt string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ','
MAP KEYS TERMINATED BY '!'
LINES TERMINATED BY '\n'
STORED AS ORC
